### ISSUE TITLE
How to self host?

### ISSUE THREAD

**Issue by moonpiedumplings** [wearrrrr/Alu#1]
I can access index.html, but I encounter an error when trying to use a proxy. Rather than accessing the proxy, it tries to access http://r.localhost/ and http://uv.localhost, and the page doesn't load.

**Comment by myschoolisass** [comment]
did you download it and then go to the zipped file, or did you try to use it on a deployment service?

**Comment by wearrrrr** [comment]
Irrelevant issue, Alu has been completely updated and should work fine now :)
