### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Playboyjusthegreat27** [wearrrrr/Alu#2]
Say internal server error when loading sites plz fix

**Comment by wearrrrr** [comment]
Please provide an image of the error and any logs that may show up when you try to run Alu. If you are talking about aluu.xyz, it is working perfectly fine.

**Comment by Playboyjusthegreat27** [comment]
![Screenshot (3)](https://github.com/wearrrrr/Alu/assets/95702468/09646ae8-c30f-4a55-9776-7fb4a3893291)

**Comment by Playboyjusthegreat27** [comment]
that's what I see when I try to launch a website otherwise it works fine

**Comment by wearrrrr** [comment]
I'm pretty sure this is an issue with stale service workers, im pushing an update to hopefully fix this tomorrow.

**Comment by Playboyjusthegreat27** [comment]
new problem

**Comment by Playboyjusthegreat27** [comment]
![Screenshot (4)](https://github.com/wearrrrr/Alu/assets/95702468/40b291a1-7b09-4685-aaa4-3d31a0183c86)

**Comment by Playboyjusthegreat27** [comment]
nvm ultraviolet's just broken
